name: CD Pipeline
on:
    push:
        branches:
            - main

env:
    SLACK_FRONT_TOKEN: ${{ secrets.SLACK_FRONT_TOKEN }}

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Pull Docker image
              run: |
                  echo "Pulling latest Docker image..."
                  sudo docker pull echaf/nexus-app-front:latest

            - name: Stop Old Container
              run: |
                  echo "Stopping old container if exists..."
                  sudo docker rm -f nexus-app-front-container || true

            - name: Run Docker Container
              id: run-container
              run: |
                  sudo docker run -d -p 3000:80 --name nexus-app-front-container --build-arg VITE_API_URL='{{ ${{ secrets.VITE_API_URL }} }}' echaf/nexus-app-front

            - name: Log Docker Container Output
              run: |
                  echo "Fetching Docker container logs..."
                  sudo docker logs nexus-app-front-container || true

            - name: Slack Notification on Deployment Success
              if: success()
              run: |
                  message="✅ Deployment successful for branch *${{ github.ref_name }}*"
                  curl -X POST \
                    -H 'Content-type: application/json' \
                    -H "Authorization: Bearer ${{ secrets.SLACK_FRONT_TOKEN }}" \
                    --data "{\"channel\":\"#nexus-app-front-deployment\",\"text\":\"$message\"}" \
                    https://slack.com/api/chat.postMessage
                    

            - name: Rollback on Deployment Failure
              if: failure()
              run: |
                  echo "Deployment failed, rolling back..."
                  sudo docker rm -f nexus-app-front-container || true
                  sudo docker run -d \
                    -p 3000:80 \
                    --name nexus-app-front-container \
                    -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
                    -e PORT=3000 \
                    echaf/nexus-app-front:previous

            - name: Slack Notification on Deployment Failure
              if: failure()
              run: |
                  message="❌ Deployment failed for branch *${{ github.ref_name }}*\nInitiating rollback..."
                  curl -X POST \
                    -H 'Content-type: application/json' \
                    -H "Authorization: Bearer ${{ secrets.SLACK_FRONT_TOKEN }}" \
                    --data "{\"channel\":\"#nexus-app-front-deployment\",\"text\":\"$message\"}" \
                    https://slack.com/api/chat.postMessage
